# -*- coding: utf-8 -*-
"""MBA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glZ7tmKq5cBWaN9ziAAYtwV5OhXtFoXp
"""

import time

# Start the timer for the entire code execution
start_time_total = time.time()

"""Tambahkan kode di bawah ini di bagian yang ingin Anda ukur waktu eksekusinya, misalnya saat memuat library atau melatih model."""

# Example: Measuring time for library import (this is just for demonstration)
start_time_library = time.time()
# import your library here
end_time_library = time.time()
print(f"Time taken for library import: {end_time_library - start_time_library:.4f} seconds")

# Example: Measuring time for model training (add your model training code here)
# start_time_model = time.time()
# # your model training code
# end_time_model = time.time()
# print(f"Time taken for model training: {end_time_model - start_time_model:.4f} seconds")

# End the timer for the entire code execution
end_time_total = time.time()
print(f"Total execution time: {end_time_total - start_time_total:.4f} seconds")

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import pandas as pd
import numpy as np

# Baca file CSV
data = pd.read_csv("MBA.csv")

# Bersihkan nama kolom dari spasi berlebih (jaga-jaga)
data.columns = data.columns.str.strip()

# Remove the 'race' column
data = data.drop(columns=['race'], errors='ignore')

# Ensure 'gpa' column is treated as a decimal
if 'gpa' in data.columns:
    # Replace comma with period if it exists, then convert to numeric
    data['gpa'] = data['gpa'].astype(str).str.replace(',', '.', regex=False)
    data['gpa'] = pd.to_numeric(data['gpa'], errors='coerce')

# Ubah kolom kategorikal menjadi numerik (Label Encoding sederhana)
# Adjust categorical columns based on the MBA.csv data
# Removed 'work_industry' from the list to keep it as object type
categorical_cols = ['gender', 'international', 'major', 'admission']
for col in categorical_cols:
    if col in data.columns:
        # Simpan mapping sebelum encoding
        mapping = dict(enumerate(data[col].astype('category').cat.categories))
        data[col] = data[col].astype('category').cat.codes
        print(f"Mapping untuk kolom '{col}':")
        print(mapping)
        print("-" * 20)

# Handle missing values in 'admission' column (encoded as -1)
if 'admission' in data.columns:
    # Replace -1 with NaN
    data['admission'] = data['admission'].replace(-1, np.nan)
    # Fill missing values with the value for 'Waitlist' (which is 1 based on the mapping)
    data['admission'].fillna(1, inplace=True)
    # Convert back to integer type
    data['admission'] = data['admission'].astype(int)


# --- Tampilan hasil ---
print("\nPreview data setelah pemrosesan:")
# Tampilkan kolom yang relevan dengan data MBA.csv
# display(data.head()) # Commented out as requested

print("\nInfo kolom setelah pemrosesan:")
print(data.info())

print("\nCek missing values:")
print(data.isnull().sum())

"""# Task
Simpan model Decision Tree yang telah dibuat ke dalam file `model.pkl` dan sediakan untuk diunduh.

## Simpan model

### Subtask:
Simpan objek model Decision Tree (`decision_tree_model`) ke dalam file `model.pkl` menggunakan library `joblib`.

**Reasoning**:
Save the trained Decision Tree model to a file using joblib.
"""

import joblib

# Save the trained model to a file
joblib.dump(decision_tree_model, 'model.pkl')

"""## Sediakan untuk diunduh

### Subtask:
Berikan kode atau instruksi kepada pengguna untuk mengunduh file `model.pkl` yang telah disimpan.

**Reasoning**:
Provide instructions and code for the user to download the saved model file.
"""

# Instruksi untuk mengunduh file model:
print("Model Decision Tree telah disimpan ke dalam file 'model.pkl'.")
print("Untuk mengunduh file ini, jalankan kode di bawah:")
print("from google.colab import files")
print("files.download('model.pkl')")

# Kode untuk mengunduh file model (jika dijalankan di Google Colab)
try:
    from google.colab import files
    files.download('model.pkl')
except ImportError:
    print("\nPastikan Anda menjalankan kode ini di lingkungan Google Colab untuk mengunduh file.")
    print("Jika tidak, Anda mungkin perlu menggunakan metode lain untuk mengakses file 'model.pkl'.")